language: python
python:
    - "2.7"
matrix:
    exclude:
        - python: "2.7"
    include:
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py26
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py26
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py26-gevent
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py26-gevent
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py26-eventlet
        - python: "2.6"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py26-eventlet
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py27
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py27
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py27-gevent
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py27-gevent
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py27-eventlet
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py27-eventlet
        - python: "2.7"
          env: ZOOKEEPER_VERSION=3.5.0-alpha TOX_VENV=py27-gevent
        - python: "3.3"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py33
        - python: "3.3"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py33
        - python: "3.4"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=py34
        - python: "3.4"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=py34
        - python: "pypy"
          env: ZOOKEEPER_VERSION=3.3.6 TOX_VENV=pypy
        - python: "pypy"
          env: ZOOKEEPER_VERSION=3.4.6 TOX_VENV=pypy

notifications:
  email: false

before_install:
    - sudo apt-get install libevent-dev

install:
    - pip install tox

script:
    - make test
