language: python
python:
    - "2.6"
    - "2.7"

env:
    - GEVENT_VERSION=0.13.8
    - GEVENT_VERSION=1.0b3
    - ZOOKEEPER_VERSION=3.3.6
    - ZOOKEEPER_VERSION=3.4.3

notifications:
  email:
    - hschlichting@mozilla.com
    - ben@groovie.org
  irc: "irc.mozilla.org#services-dev"

before_install:
    - sudo apt-get install libevent-dev

install:
    - make
    - make zookeeper

script:
    - make test
