sudo: false
dist: xenial
addons:
  apt:
    packages:
    - libevent-dev
    - krb5-kdc
    - krb5-admin-server
cache:
  pip: true
  directories:
  - zookeeper
language: python
python:
- '2.7'
matrix:
  exclude:
  - python: '2.7'
  include:
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py27
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py27
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py27-gevent
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py27-gevent
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py27-eventlet
  - python: '2.7'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py27-eventlet
  - python: '3.6'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py36
  - python: '3.6'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py36-sasl
  - python: '3.6'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py36
  - python: '3.6'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py36-sasl
  - python: '3.7'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py37
  - python: '3.7'
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=py37-sasl
  - python: '3.7'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py37 DEPLOY=true
  - python: '3.7'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=py37-sasl
  - python: pypy
    env: ZOOKEEPER_VERSION=3.4.14 TOX_VENV=pypy
  - python: 'pypy'
    env: ZOOKEEPER_VERSION=3.5.6 ZOOKEEPER_PREFIX="apache-" ZOOKEEPER_SUFFIX="-bin" ZOOKEEPER_LIB="lib" TOX_VENV=pypy
notifications:
  email: false
install:
- pip install tox
script:
- make test
deploy:
  provider: pypi
  user: bbangert
  password:
    secure: L9yXZ2PhQ2wJKQkgigIzW3f/a3ajzUamMdThVelcp/NZeTJfzlC/t89lfSRwLh95o9Z/aIxC4T8yZvNrRzzyMEP0O6s1F69pVm5Px+KBuv82lmI7p5sKTYPp35CE9jH+K/52Fy0+Az5F502xLrkaO4VLLA+zhLffw/qyvNbZui0=
  on:
    tags: true
    condition: $DEPLOY = true
  distributions: release
  skip_upload_docs: true
