language: python
python:
    - "2.7"
matrix:
    exclude:
        - python: "2.7"
    include:
        - python: "2.6"
          env: GEVENT_VERSION=0.13.8 ZOOKEEPER_VERSION=3.3.6
        - python: "2.6"
          env: GEVENT_VERSION=0.13.8 ZOOKEEPER_VERSION=3.4.6
        - python: "2.6"
          env: GEVENT_VERSION=1.0.1 ZOOKEEPER_VERSION=3.3.6
        - python: "2.6"
          env: GEVENT_VERSION=1.0.1 ZOOKEEPER_VERSION=3.4.6
        - python: "2.7"
          env: GEVENT_VERSION=0.13.8 ZOOKEEPER_VERSION=3.3.6
        - python: "2.7"
          env: GEVENT_VERSION=0.13.8 ZOOKEEPER_VERSION=3.4.6
        - python: "2.7"
          env: GEVENT_VERSION=1.0.1 ZOOKEEPER_VERSION=3.3.6
        - python: "2.7"
          env: GEVENT_VERSION=1.0.1 ZOOKEEPER_VERSION=3.4.6
        - python: "2.7"
          env: GEVENT_VERSION=1.0.1 ZOOKEEPER_VERSION=3.5.0-alpha
        - python: "3.3"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "3.3"
          env: ZOOKEEPER_VERSION=3.4.6
        - python: "3.4"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "3.4"
          env: ZOOKEEPER_VERSION=3.4.6
        - python: "pypy"
          env: ZOOKEEPER_VERSION=3.3.6
        - python: "pypy"
          env: ZOOKEEPER_VERSION=3.4.6

notifications:
  email: false

before_install:
    - sudo apt-get install libevent-dev

install:
    - make
    - make zookeeper

script:
    - make test
